version: "3"

services:
  broker-service:
    build:
      context: ./broker-service
      dockerfile: ./broker-service.dockerfile
    container_name: broker-service
    restart: always
    ports:
      - "8080:8080"
    deploy:
      mode: replicated
      replicas: 1

  auth-service:
    build:
      context: ./auth-service
      dockerfile: ./auth-service.dockerfile
    container_name: auth-service
    restart: always
    ports:
      - "8081:8080"
    deploy:
      mode: replicated
      replicas: 1
